trainee.data.path=classpath:trainees.txt
trainer.data.path=classpath:trainers.txt
training.data.path=classpath:trainings.txt
user.data.path=classpath:users.txt

#for debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG


spring.messages.basename=messages
spring.messages.encoding=UTF-8