spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.test.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.test.datasource.username=sa
spring.test.datasource.password=1234
spring.test.datasource.driver-class-name=org.h2.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql


#for debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG


spring.messages.basename=messages
spring.messages.encoding=UTF-8