# App
spring.application.name=gym-crm
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres-db:5432/gym_crm
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.h2.console.enabled=true


# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# ActiveMQ / JMS
spring.activemq.broker-url=tcp://activemq:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.activemq.packages.trust-all=true


# OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Logging
logging.level.root=INFO
