spring.datasource.url=jdbc:postgresql://localhost:5432/gym_local
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Custom app props
app.env=LOCAL

