spring.application.name=gym-crm
server.port=8080
#trainer.workload.url=http://localhost:8081

spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

#for production without "DROP TABLE..." as in schema.sql, in order NOT to delete existing data
#spring.sql.init.mode=never
#for using current schema.sql & data.sql just for testing current project
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


management.endpoints.web.exposure.include=info,health,metrics,beans,env,loggers,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true

#spring.profiles.active=staging

logging.level.org.springframework.security=TRACE


#for debugging
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG

spring.messages.basename=messages
spring.messages.encoding=UTF-8

jwt.secret=DS0gOUbJs5B1Rc9Q+/WQ66Cn9QnGlyOvhpJWIsz5cR4=
jwt.expiration-ms=3600000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true